markdown: redcarpet
google_analytics: UA-36064433-1
adsense_client: ca-pub-0370307907399937

url: https://www.buildandshoot.com
title: Build and Shoot
description: Build and Shoot is a player-run community for the online voxel FPS game based on Ace of Spades Classic. Login to play the game, interact with players, and customize your experience - it's all 100% free!
forum_feed: https://www.buildandshoot.com/forums/app.php/feed/news